I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 183, in script
    show expression manga0 at manga_zoom
  File "game/script.rpy", line 183, in <module>
    show expression manga0 at manga_zoom
NameError: name 'manga0' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 183, in script
    show expression manga0 at manga_zoom
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 1124, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 1080, in show_imspec
    expression = renpy.python.py_eval(expression)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 183, in <module>
    show expression manga0 at manga_zoom
NameError: name 'manga0' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Double Poision 2 1.0
Fri Jul  4 04:40:24 2025
