I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 740, in script
    call screen camera_preview_ui
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
Exception: DynamicImage 'camera/[current_location]-bg.png': could not find image. ('camera/desk_top-bg.png')

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 740, in script
    call screen camera_preview_ui
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 1987, in execute
    self.call("execute")
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 1966, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\statements.py", line 374, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\exports\statementexports.py", line 345, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\display\core.py", line 2218, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\display\core.py", line 2748, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\display\screen.py", line 485, in visit_all
    self.child.visit_all(callback, seen=None)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\display\displayable.py", line 436, in visit_all
    callback(self)
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\display\core.py", line 2748, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\display\image.py", line 793, in per_interact
    self.find_target()
  File "C:\Users\August\Downloads\renpy-8.3.7-sdk\renpy\display\image.py", line 683, in find_target
    raise Exception(error)
Exception: DynamicImage 'camera/[current_location]-bg.png': could not find image. ('camera/desk_top-bg.png')

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Double Poision 2 1.0
Fri Jul 18 23:59:24 2025
